server:
  port: 9007
#spring:
#  cloud:
#    config:
#      retry:
#        # 配置重试次数，默认为6
#        max-attempts: 6
#        # 间隔乘数，默认1.1
#        multiplier: 1.1
#        # 初始重试间隔时间，默认1000ms
#        initial-interval: 1000
#        # 最大间隔时间，默认2000ms
#        max-interval: 2000
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: prod
      uri: http://127.0.0.1:9006/
